# Generated by Django 5.2.6 on 2025-11-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_song_audio_file_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
